---
- name: Install ntp packages
  apt: pkg={{ item }} state=present
  with_items:
    - ntp
    - ntpdate
  become: yes

- name: Ensure ntpd enabled at boot and started
  service: name=ntp state=started enabled=yes
  become: yes
