---
- name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Install bash packages
  apt: pkg={{ item }} state=present
  with_items:
    - xclip
    - htop
    - curl
    - pkg-config
  become: yes

- name: Setting bash aliases
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - bash aliases"
    content: |
      alias ..="cd .."
      alias bc='bc -l'
      alias pbcopy='xclip -sel clip'
      alias DIR='echo "DIR=\"\$( cd \"\$( dirname \"\${BASH_SOURCE[0]}\" )\" && pwd )\""'

- name: Creating cdr function
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - cdr function"
    content: |
      # Walk backwards until you hit a "root" folder
      function cdr() {
        # for git repos we can make 1 jump
        git_root=`git rev-parse --show-toplevel 2> /dev/null`
        if [ "$git_root" != "" ]
        then
          cd $git_root
          return 0
        fi
      }

