---
- name: Add google-chrome key
  apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present
  become: yes
  notify:
    - update apt

- name: add google-chrome repo
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: 'google-chrome'
  become: yes
  notify:
    - update apt

- name: install google-chrome
  apt:
    pkg: google-chrome-stable
  become: yes
