---
- name: install git
  apt: name=git state=present

- file:
    path: "{{ ansible_env.HOME }}/.ssh/github"
    state: directory
    mode: 0700

- name: github ssh key
  shell: ssh-keygen -b 8192 -t rsa -f {{ ansible_env.HOME }}/.ssh/github/id_rsa -q -N ""
  args:
    creates: "{{ ansible_env.HOME }}/.ssh/github/id_rsa"

- name: Ensure ~/.ssh directory exists
  file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory

- name: Setting github ssh config
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.ssh/config"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - github ssh config"
    create: yes
    mode: 0600
    content: |
      Host github.com
          HostName github.com
          User git
          IdentityFile {{ ansible_env.HOME }}/.ssh/github/id_rsa

- name: Git global configs
  git_config:
    name={{item.name}}
    scope=global
    value={{item.value}}
  with_items:
    - {name: 'color.ui', value: 'true'}
    - {name: 'alias.lg', value: 'log --graph --pretty=format:"%Cred%h%Creset - %s %Cgreen(%cD) %C(bold blue)<%an>%Creset %C(yellow)%d%Creset" --abbrev-commit'}

- name: Add git bash completion
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - git bash completion"
    content: |
      if [ -f /etc/bash_completion.d/git-prompt ]; then
        . /etc/bash_completion.d/git-prompt
      fi

- name: bash PS1 prompt
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    regexp: '^PS1='
    line: PS1='${debian_chroot:+($debian_chroot)}\[\033[01;34m\]\u@\h\[\033[00m\]:\[\033[01;32m\]\w\[\033[0;31m\]$(__git_ps1)\[\033[00m\]\n\$ '

- name: show dirty git directory indicator
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    line: export GIT_PS1_SHOWDIRTYSTATE=1
