---
- name: Install cli tools
  apt: pkg={{ item }} state=present
  with_items:
    - python-virtualenv
    - python3-virtualenv
    - libsnappy-dev
    - python-dev
    - python3-dev
    - libssl-dev
  become: yes
