---
- name: Install pen testing cli tools
  apt: pkg={{ item }} state=present
  with_items:
    - aircrack-ng
    - dsniff
    - ettercap-common
    - macchanger
    - medusa
    - nmap
    - sqlmap
  become: yes
