---
# Note: network-manager < 1.4 has a bug that will reset
# the interface mac address.
- name: preserve mac address for ethernet
  ini_file:
    dest: /etc/NetworkManager/NetworkManager.conf
    section: connection
    option: ethernet.cloned-mac-address
    value: preserve
  become: yes

- name: set random mac address for wifi
  ini_file:
    dest: /etc/NetworkManager/NetworkManager.conf
    section: connection
    option: wifi.cloned-mac-address
    value: random
  become: yes
