---
- name: Install graphics packages
  apt: pkg={{ item }} state=present
  with_items:
    - gimp
    - xsane
    - xscreensaver
    - xdotool
    - graphviz
  become: yes

- name: Remove light-locker install to prevent locking problems
  apt: pkg=light-locker state=absent
  become: yes
