---
- name: Install dependencies
  apt: name={{ item }}
  with_items:
    - apt-transport-https
    - ca-certificates
    - python-pip
  sudo: yes

- name: Add GPG key
  apt_key:
    url: https://apt.dockerproject.org/gpg
    state: present
    id: 2C52609D
  sudo: yes

- name: Add docker apt repo
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main"
    state: present
  sudo: yes

- name: Install Docker
  apt: name=docker-engine
  sudo: yes
