---
- name: Install dependencies
  apt: name={{ item }}
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
  become: yes

- name: add docker-ce GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    id: 0EBFCD88
  become: yes

- name: Add docker apt repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu yakkety stable"
    # disable until stable zesty release is available
    # repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  become: yes

- name: install docker-ce
  apt:
    name: docker-ce
    state: present
  become: yes
